#!/usr/bin/env python
from multiprocessing import Process
from redis import Redis

from newsflow.config import conf, logger
from newsflow.consumer import DownloadConsumer

def main():
    log = logger('newsflow.main')

    db = Redis(conf('redis.server'), db=conf('redis.db'))
    log.info('Starting newsflow consumer')

    consumer = DownloadConsumer(conf('scraper.server'), username=conf('scraper.username'), password=conf('scraper.password'), database=db)
    consumer.run()

if __name__ == '__main__':
    main()
