#!/usr/bin/env python
from multiprocessing import Process
from redis import Redis

from newsflow.config import conf, logger

import os.path
import os

def main():
    log = logger('newsflow.main')

    db = Redis(conf('redis.server'), db=conf('redis.db'))
    log.info('Starting newsflow reindex producer')

    nzbdir = conf('scraper.nzb_path')
    for group in conf('scraper.groups'):
        groupdir = os.path.join(nzbdir, group)
        for filename in os.listdir(groupdir):
            print group, filename
            db.lpush('queue/index_nzb', '%s/%s' % (group, filename))

if __name__ == '__main__':
    main()
