#!/usr/bin/env python
from newsflow.config import conf, logger
from newsflow.search import application
from redis import Redis

from wsgiref.simple_server import make_server, WSGIRequestHandler
from threading import Thread
from time import sleep

def run_wsgi():
    # Disable reverse DNS upon request. It's just stupid.
    def address_string(self):
        return self.client_address[0]
    WSGIRequestHandler.address_string = address_string

    server = make_server(
        conf('http.bind_address'),
        conf('http.bind_port'),
        application)
    server.serve_forever()

def main():
    log = logger('newsflow.main')

    log.info('Starting newsflow webserver')
    run_wsgi()

if __name__ == '__main__':
    main()
